version: "3.7"

services:
  rtp-api:
    image: alexburlacu/rtp-server:faf18x
    ports:
      - 4000:4000
  lab1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rtp-api